### ISSUE TITLE
Website unknown error

### ISSUE THREAD

**Issue by NewVo1d** [reactjs/zh-hans.reactjs.org#1072]
React中文文档 Beta站点中
LearnReact-增加互动性-[更新state中的数组](https://beta.react.jscn.org/learn/updating-arrays-in-state)章节访问异常

截图如下：
![image](https://user-images.githubusercontent.com/89888306/221348519-6fa114ec-68f5-4eb5-88d5-1ea814652ad9.png)

**Comment by awxiaoxian2020** [comment]
@NewVo1d 我发现是标题级别错误造成的，你愿意提 PR 解决这个问题吗？
![bug](https://user-images.githubusercontent.com/69554233/221389047-8efc99c9-44ca-472e-bd16-a88e15b07ce3.png)

**Comment by NewVo1d** [comment]
> @NewVo1d 我发现是标题级别错误造成的，你愿意提 PR 解决这个问题吗？ ![bug](https://user-images.githubusercontent.com/69554233/221389047-8efc99c9-44ca-472e-bd16-a88e15b07ce3.png)

没问题，稍后我看一下就提PR。

**Comment by NewVo1d** [comment]
@awxiaoxian2020 你好，我暂时没发现标题级别有错误。

上述图片中正确的标题级别是否是第三级？目前main分支 [update-arrays-in-state](https://github.com/reactjs/zh-hans.reactjs.org/blob/main/beta/src/content/learn/updating-arrays-in-state.md?plain=1) 中的标题级别是正确的。

或许是我哪里理解错误？烦请指正。

**Comment by awxiaoxian2020** [comment]
我已经给出了 diff，直接按照图片的修改方式修改即可。若有疑问，请参照英文仓库标题级别进行更改

**Comment by NewVo1d** [comment]
> 我已经给出了 diff，直接按照图片的修改方式修改即可。若有疑问，请参照英文仓库标题级别进行更改

了解，#1073 中已修正。
