### ISSUE TITLE
The website zh-hans.reactjs.org is inaccessible.

### ISSUE THREAD

**Issue by symant233** [reactjs/zh-hans.reactjs.org#1091]
It seems vercel build had broken. [zh-hans.reactjs.org](https://zh-hans.reactjs.org)
```
404: NOT_FOUND
```
If this site is deprecated, it should be redirected to `react.jscn.org`

**Comment by awxiaoxian2020** [comment]
The old website has been achived recently. We release the new docs immediately for a better sync maintainence to avoid conflicts next time. But we have no access for the official vercel to set up the new website. So we deploy the site https://react.jscn.org as a temp substitute.

We may be able to track it at https://github.com/reactjs/react.dev/issues/4135.

**Comment by awxiaoxian2020** [comment]
Now, it's accessible!
