### ISSUE TITLE
询问翻译进程

### ISSUE THREAD

**Issue by LiMao00** [reactjs/zh-hans.reactjs.org#1096]
现在翻译进程怎么样，任务认领好像也是21年的
respect

**Comment by awxiaoxian2020** [comment]
近期官方刚刚正式发布了新的站点，翻译进程列表将会于近期更新，尽请期待。另外有关于翻译进程的问题，请关注https://github.com/reactjs/react.dev/issues/4135#issuecomment-1479889028
相关问题和讨论请移步至https://github.com/reactjs/zh-hans.reactjs.org/discussions/1089. 我将关闭这个 issue.
感谢支持！
