### ISSUE TITLE
有个错别字

### ISSUE THREAD

**Issue by xesam** [reactjs/zh-hans.reactjs.org#185]
文件：[https://github.com/reactjs/zh-hans.reactjs.org/blob/master/content/docs/context.md ](https://github.com/reactjs/zh-hans.reactjs.org/blob/master/content/docs/context.md#api-api )

![微信图片_20190330165123](https://user-images.githubusercontent.com/1892804/55273893-4db60c00-530c-11e9-80ed-2bef34e88721.png)

**Comment by QC-L** [comment]
THX！已更正
