### ISSUE TITLE
翻译建议

### ISSUE THREAD

**Issue by aximario** [reactjs/zh-hans.reactjs.org#187]
高级指引 -> 深入 JSX -> ”属性扩散“ 翻译为 “属性展开“ 应该会更容易理解一些
[https://zh-hans.reactjs.org/docs/jsx-in-depth.html](深入 JSX)

**Comment by QC-L** [comment]
我看下，稍等

**Comment by QC-L** [comment]
@aximario 已修复，查看 #188
