### ISSUE TITLE
link within "HOC" page is not found

### ISSUE THREAD

**Issue by saranshkataria** [reactjs/zh-hans.reactjs.org#256]
Copying issue from reactjs/reactjs.org#2082

In [HOC page](https://zh-hans.reactjs.org/docs/higher-order-components.html), the link **[阅读更多 关于我们为什么要抛弃 mixins](https://zh-hans.reactjs.org/blog/2016/07/13/mixins-consideration-hazardous.html)** will lead to a "404" page.

May need to change the link to point this English version:  https://reactjs.org/blog/2016/07/13/mixins-considered-harmful.html   , if no Chinese version available now.

**Comment by lexiaoau** [comment]
In title, it is "link", not "ink".

**Comment by saranshkataria** [comment]
> In title, it is "link", not "ink".

fixed, thanks

**Comment by QC-L** [comment]
@saranshkataria thanks，I'll fix it.

**Comment by QC-L** [comment]
DONE! @saranshkataria [commit](https://github.com/reactjs/zh-hans.reactjs.org/commit/15aab79e24058334be75b6862aec3d2d63627ccb)
