### ISSUE TITLE
Need reword in Hook 概览

### ISSUE THREAD

**Issue by lexiaoau** [reactjs/zh-hans.reactjs.org#258]
React 会在组件销毁或者后续渲染重新执行副作用函数时取消对 ChatAPI 的订阅。

should be:

React 会在组件销毁或者后续渲染**时**重新执行副作用函数取消对 ChatAPI 的订阅。

**Comment by QC-L** [comment]
@lexiaoau fixed it. [commit](https://github.com/reactjs/zh-hans.reactjs.org/commit/194577ecdb536467a6a40963ab81b8132768252c)
