### ISSUE TITLE
Modify zh-hans.reactjs.org/content/docs/hooks-state.md Line 247 of the content api name

### ISSUE THREAD

**Issue by laishiwen** [reactjs/zh-hans.reactjs.org#259]
#### Administrator, please ```'useSatate'``` replace ```'useState'```

**Comment by laishiwen** [comment]
![微信图片_20190630154802](https://user-images.githubusercontent.com/17078631/60393922-3b3bb080-9b4f-11e9-8d43-f8ffa3988fcd.png)

**Comment by QC-L** [comment]
@laishiwen I'll fix it. THX!

**Comment by QC-L** [comment]
Fied! [commit](https://github.com/reactjs/zh-hans.reactjs.org/commit/7e499ec1eab94b32d9a0bcea75ba7e5d51cf330d)

**Comment by laishiwen** [comment]
give the thumbs-up!




------------------ 原始邮件 ------------------
发件人: "QiChang Li"<notifications@github.com>;
发送时间: 2019年6月30日(星期天) 下午5:31
收件人: "reactjs/zh-hans.reactjs.org"<zh-hans.reactjs.org@noreply.github.com>;
抄送: "Sven"<467158536@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [reactjs/zh-hans.reactjs.org] Modifyzh-hans.reactjs.org/content/docs/hooks-state.md Line 247 of the content apiname (#259)




Closed #259.
