### ISSUE TITLE
The "Arrow Function" link 404 in the article is invalid. 文章内的“箭头函数”链接404失效了

### ISSUE THREAD

**Issue by shanlanCoding** [reactjs/zh-hans.reactjs.org#292]
The "Arrow Function" link 404 in the article is invalid.
> The [arrow function ](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Functions/Arrow_function) is used above, but the same can be done with ordinary functions:
The correct arrow function link should be: https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Functions/Arrow_functions.

------------

文章内的“箭头函数”链接404失效了，原文：
> 上面使用了[箭头函数](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Functions/Arrow_function)，不过使用普通的函数也同样可以：

正确的箭头函数链接应该为：https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Functions/Arrow_functions

**Comment by QC-L** [comment]
THX! 我修正一下

**Comment by QC-L** [comment]
fix in #293
