### ISSUE TITLE
发现一个渲染文档bug

### ISSUE THREAD

**Issue by zhangenming** [reactjs/zh-hans.reactjs.org#306]
https://zh-hans.reactjs.org/docs/render-props.html
译文
![image](https://user-images.githubusercontent.com/21235555/64428198-be482c80-d0e5-11e9-998d-470d2c752605.png)
原文是
![image](https://user-images.githubusercontent.com/21235555/64428347-1848f200-d0e6-11e9-93d5-c4abca9c3afc.png)

但中文渲染成了
![image](https://user-images.githubusercontent.com/21235555/64428318-0404f500-d0e6-11e9-8394-d103f439319c.png)

把原文的文本\<Cat> 渲染成cat dom 元素了, 导致语句不通

**Comment by yuqingc** [comment]
谢谢指出，应该是遗漏了 反引号

**Comment by yuqingc** [comment]
Fixed by #307, waiting to be merged.

**Comment by QC-L** [comment]
THX!
