### ISSUE TITLE
error close Tag

### ISSUE THREAD

**Issue by ZuccRoger** [reactjs/zh-hans.reactjs.org#385]
here a error close Tag
in end of button 
please fix it! thank you

<img width="913" alt="截屏2020-03-25上午11 19 57" src="https://user-images.githubusercontent.com/37689108/77498785-71625280-6e8b-11ea-9579-67133b2edefb.png">

**Comment by yuqingc** [comment]
Sorry I don't think there are any errors in those snippets. I'll close this issue along with #386 & #387 . Feel free to reopen it if you have any questions on this. Thanks for your issue. 😄
