### ISSUE TITLE
some error in proptypes in react file

### ISSUE THREAD

**Issue by lin-fy** [reactjs/zh-hans.reactjs.org#420]
Recently, I was studying react to see the document of proptypes，i found the case of proptypes causes console to report an error

error tips: Warning: Component Person declared `PropTypes` instead of `propTypes`. Did you misspell the property assignment?

**Comment by QC-L** [comment]
Which file are you talking about? @lin-fy

**Comment by lin-fy** [comment]
sorry，It's my fault. I thought I was closed the comment
