### ISSUE TITLE
Unofficial blog posts should not be on the React blog

### ISSUE THREAD

**Issue by gaearon** [reactjs/zh-hans.reactjs.org#463]
Hi folks!

I've noticed there are multiple blog posts that were **not** written by the React team:

https://zh-hans.reactjs.org/blog/2020/08/21/react-hooks-extra-level-of-indirection.html
https://zh-hans.reactjs.org/blog/2020/08/22/react-hooks-state-granularity.html

While I appreciate that someone wanted to share them, we should not post them on the official blog translation because the React team did not vet their content. It is very important for the React blog to be a resource people can trust, so it needs to match 1:1 to what is being published in English. Please take these posts down and move them to a personal blog. Thank you!

**Comment by yuqingc** [comment]
I think these unofficial posts & components should also be removed:

- https://zh-hans.reactjs.org/blog/2020/05/22/react-hooks.html
- External Logo & QR code at the bottom left of  the [Home page](https://zh-hans.reactjs.org/)

**Comment by QC-L** [comment]
@gaearon DONE! It was my mistake.

**Comment by gaearon** [comment]
Thank you for quick action!
