### ISSUE TITLE
Wording of the translation of "composition"

### ISSUE THREAD

**Issue by Neo42** [reactjs/zh-hans.reactjs.org#519]
Hi @gaearon and anyone who is making React better and speaks English, pardon me for disturbing you with this. But I believe this is about how we Chinese developers should understand React and you're probably the best ones to turn to when it comes to this issue, as we all know that you all have been innovating React and likely to understand the concepts better than most of us. 

I know all of you guys might have things to attend to, so I have to mention more than one person in this one. Sorry for that.🙏🏻

**TLDR** 
**To translate "(component) composition" and "composing (components)" into Chinese, should we use "组合"(meaning combining in some way，no specific meaning of nesting or passing things as arguments) or "复合"(meaning what "composition" means in function composition)? Or, in another word, when you say "component composition", do you really mean "putting components together and no more than that" or "passing components as arguments into components to form new ones"?**

Please fact-check me on this one. As far as I know, "component composition" (or "composing components") in react comes from function composition in functional programming. Therefore, the translations for "component composition" and "function composition" should share consistency. And the idea of passing components as arguments into components should be kept in the former.

As far as I know, in Chinese, "function composition", as defined in [math](https://en.wikipedia.org/wiki/Function_composition) and [computer science](https://en.wikipedia.org/wiki/Function_composition_(computer_science)), should be only translated into ["函数复合"](https://zh.wikipedia.org/wiki/%E5%A4%8D%E5%90%88%E5%87%BD%E6%95%B0), not "函数组合" (combining functions in some way). And "component composition" should be translated into "组件复合", not "组件组合". Because the term "composition" and its formal translation "复合" were coined upfront. Once we use another word instead, the idea of passing things as arguments to form new ones will be lost. It's like only "composition" can be used for "function composition". You can't use "combination" for "function composition" or "component composition" because that ain't what you mean. And BTW, as you probably know, [function combination, meaning combining functions into new ones by applying arithmetic operations](http://dl.uncw.edu/digilib/Mathematics/Algebra/mat111hb/functions/combine/combine.html), does exist in math. That is also a critical reason why we should be careful about these words.

**But here is the problem (probably).** "Composing" and "composition" in the React doc (Chinese version) **ARE** translated into "组合"(combining in some way, no specific meaning of nesting or passing things as arguments), not "复合", the formal translation for "composition". What's more, the word "combination" is also translated into "组合". That means if you come across these two words "combination" and "composition" at the same time in the doc (Chinese version), you won't notice any difference. And that, I think, is a major problem that should be fixed immediately, since composition is the core idea of React.

We've been discussing this in our group since yesterday. Some of us say that we don't have to modify it to "复合", as, in Chinese, the word "组合" is a commonly-seen word that is much more familiar to most of the users and way easier to read & understand. But I would argue that accuracy comes first. Some say we should keep the English word since it can mean a lot of things and we can't be sure about what it actually means, which I think is avoiding the problem. And so far only I suggest that we should go with "复合" for "composition" instead of "组合".

So I have to ask you for help on this one because you have always been involved in the wording process. If I'm wrong, I'm wrong, lesson learned. And I would appreciate your correction. But please share your opinion: should we go with "组合"(combining in some way) or "复合"("composition" in function composition)?

Thank you for your time.

**P.S. If you were to use Google Translate to translate between these words, please don't. You can't trust GT this time. Please go to Wikipedia directly. And check out the Chinese version as well, if you will.**

**Comment by gaearon** [comment]
I think reusing the term from functional programming makes sense to me. It’s true people have to learn what it means but you kind of have to do that anyway so you might as well know about it. But I’d like to hear more arguments for and against from native speakers.

One other option could be to translate it contextually. For example, in places where the technical meaning isn’t important, you could leave “combining”, but in places specifically focused on composition techniques you could use the more technical term.

**Comment by Neo42** [comment]
@gaearon Thanks for the explanation!

**Comment by robertying** [comment]
We've been talking about this for days in the translation group.

@Neo42 insists that we should use 复合 instead 组合 for `composition`.

His claim is mostly based on the transferred concept from `function composition` which uses 复合. However, 复合 is really not a good word in my opinion.

## Why not 复合 (that @Neo42 is proposing)

- 复合 as compositing is a technical term that not many people would use daily and it can cause understanding obstacles.
  
>I think reusing the term from functional programming makes sense to me. It’s true people have to learn what it means but you kind of have to do that anyway so you might as well know about it.

Yes this is true sometimes. But we need to take into consideration how many people have had a solid understanding of `function composition` or `functional programming` when they start to learn React or JS. If not, how much more mental burden they would have if they realize they may not have a good understanding of the term `composition` unless they consult with Wikipedia or some math textbooks.

- 复合 itself consists of many meanings in Chinese when put in words without sufficient context.

  复 in 复合 have two common meanings: `back again` and `duplicate or have parts in common`. 复合 can be misunderstood as `back again together` when taken the first meaning of 复. And I think `composition` is not so frequently seen with `function` to erase the ambiguity for starting learners.

## Why 组合 (current translation)

组合 is more commonly seen and better represents React philosophy in my opinion. 

- 组合 is less ambiguous

组合 simply means assembling. People would think building React components is like building Lego. This makes more sense for beginners and is a lot like how we write React - using JSX.

- 组合 can make a strong comparison with `inheritance`

组合 does not imply the order or importance of its assembling parts aka components. This gives a contextual hint that `composition` and `inheritance` are different ways of building stuff.

- 组合 shares the same word root **组** with **组件** (components)

How `components` are translated has yet had any arguments. It is 组件。If we use **复**合 (composition) and **组**件 (components) together, people would get really confused about naming.

## Summary

Overall for the translation of `composition`, 复合 is more related with the origin and scientific term (and may indicate how some components are passed to the other component via props), but it is less used in context and may eventually make React beginners confused, who already have a lot new concepts to deal with in the first place. 

The current translation 组合 is more intuitive and would give beginners a better picture of how React builds instead how React works. And it shares the same word root as `component`'s formal translation 组件。

## Additional Information

### Poll

We made a pool yesterday in the translation group. And @Neo42 is the only person who is for the wording changes. Others either want it the same way or not translated to avoid conflicts.

![IMG_0571](https://user-images.githubusercontent.com/22592111/113510538-fb102a00-958d-11eb-9580-5ff4840c39a2.PNG)

### My thoughts on the translation of technical docs

I do not like the way that people want translation of tech docs to be as technical as possible. This often results in texts that are hard to read or understand. We students in China have suffered a lot from translated textbooks or USSR-styled textbooks that favor name listing than storytelling. I don't think people like many new words when they first start learning. 

The purpose of docs' introduction part should be approachable to anyone without much prior knowledge. If they think they can dive deeper, they should try to read the original text in its original context.

What's the point of React doc translations if people use it as an dictionary rather a handbook?

**Comment by Neo42** [comment]
> 复合 as compositing is a technical term that not many people would use daily and it can cause understanding obstacles.
复合 as composing. Thank you!

**Comment by gaearon** [comment]
@robertying

Thank you for a rather detailed explanation. I agree that if there is no existing intuition for the stricter term, going with the more intuitive one makes perfect sense. In English this isn’t a problem because the word “compose” has other common meanings backed by intuition.

I think your argument is convincing.

**Comment by Neo42** [comment]
@gaearon I don't think so. I would argue that there is a whole lot of material that covers "composition" in Chinese. We have "对象复合" for "object composition", "类复合" for "class composition", "函数复合" for "function composition" and "继承与复合" for "inheritance vs composition". In fact, all these terms were coined upfront. There are also a lot of [courses](https://www.coursera.org/lecture/cpp-chengxu-sheji/fu-he-guan-xi-he-ji-cheng-guan-xi-4LHxO) about "composition". The explanation is there. And if you find the right material, there is your existing intuition for the stricter term.

Also, as for familiarity, I think it's related to how often you are exposed to the concept. The more you see it, the more familiar you are with it. And explanation shouldn't come before the term. Because the term is the language that precisely describes the concept.

**Comment by Neo42** [comment]
Thanks for the correction @gaearon @robertying!
