### ISSUE TITLE
文档建议,在clock中多个都是相同时间并不能证明他们是独立的

### ISSUE THREAD

**Issue by freshgeek** [reactjs/zh-hans.reactjs.org#539]
https://github.com/reactjs/zh-hans.reactjs.org/blob/master/content/docs/state-and-lifecycle.md

应该通过构造器传入date毫秒数,以此累加证明多个clock是独立的

**Comment by QC-L** [comment]
可以去给官方提建议，他们在重构文档。
中文这里和英文保持一致
