### ISSUE TITLE
第一步就卡死了……，请求补充更详细的步骤

### ISSUE THREAD

**Issue by qinyuanchunxue** [reactjs/zh-hans.reactjs.org#548]
运行环境 win10 ；node.js 版本：v14.17.0

发现的问题：
1. 运行“npx create-react-app my-app”，报错：“npm ERR! code E404”；按照 https://segmentfault.com/a/1190000020056016给出的全局安装方法已解决；
2.重新运行“npx create-react-app my-app”，提示：“npm WARN … requires a peer of … but none is installed. You must install peer dependencies yourself”；按照 https://stackoverflow.com/questions/57534295/npm-err-tracker-idealtree-already-exists-while-creating-the-docker-image-for 中的答案，升级npm到7后问题已解决；
3.重新运行“npx create-react-app my-app”，提示：“npm ERR! Tracker "idealTree" already exists”；搜到的答案没看懂……

额外的补充：
1. https://github.com/facebook/create-react-app#create-react-app-- 不建议使用全球安装，但直接运行 “npx create-react-app my-app” 同问题1

纯萌新，有没有大佬给补充下最新的 WIN平台安装步骤啊？

**Comment by qinyuanchunxue** [comment]
解决了，虽然还是有些不明白。 
3.的解决办法是 创建文件夹A，在文件夹A里运行命令 npm init 然后再运行命令 npx 。就可以了。

另外群里的大佬还给了一个解决办法，将 npx 设置为全局（未测试），这样就不用创建了文件A了，可以直接运行npx了。


还存在的疑问：为什么在 文件夹A 运行 npx 命令创建项目 my-app后，会提示 文件夹A 找不到 package.json文件呢？项目文件是 my-app 而不是 A啊？

**Comment by qinyuanchunxue** [comment]
教程 npx 命令下方的用户指南超链接，和动图不同的原因在于他们安装了 yarn，一个新的模块管理器。 执行命令 `npm i -g yarn` 后，再运行 npx 命令，一楼提到的问题3 就不会出现。

补充：2楼提到的解决办法，还需要在运行npx之前先运行 `npm init` ，给文件夹A创建一个 package.json 文件，不然的话会提示找不到 package-json文件。

**Comment by baxtergu** [comment]
@qinyuanchunxue 这里是中文版官方文档的仓库，只处理文档翻译部分的问题。`react` 相关的使用问题请移步至 [官方仓库 issue](https://github.com/facebook/react/issues)
