### ISSUE TITLE
Got any plans on translating the pages about community?

### ISSUE THREAD

**Issue by yliaz** [reactjs/zh-hans.reactjs.org#595]
I realize that the pages about community have not been translated while I was browsing the website. So I was wondering if you got any plans on translating those pages. As far as I can see, it is important to introduce the React community to people who speak Chinese.

我在浏览官网时，发现社区介绍相关的页面似乎并没有进行翻译？所以我想问一下是否有相关的翻译计划呢？我觉得把React社区介绍给说中文的朋友们还是很有必要的。

**Comment by QC-L** [comment]
Fixed! Please see #597
