### ISSUE TITLE
[New Docs] - Translate the glossary

### ISSUE THREAD

**Issue by QC-L** [reactjs/zh-hans.reactjs.org#609]
词汇表：

词汇 | 翻译
:---: | :---:
What's next | 下节预告
Code linters | 代码检查工具
In this chapter | 本章节
prop drilling | prop 逐级透传

**Comment by Neo42** [comment]
state 是不是跟以前一样不用翻译？

**Comment by Neo42** [comment]
queueing 应该怎么翻译？

例子：
1. [queues a new render](https://github.com/reactjs/zh-hans.reactjs.org/blob/beta/src/pages/learn/state-as-a-snapshot.md#:~:text=setIsSent(true)%20sets%20isSent%20to%20trueand%20queues%20a%20new%20render.)
2. [Queueing a Series of State Updates](https://github.com/reactjs/zh-hans.reactjs.org/blob/beta/src/pages/learn/queueing-a-series-of-state-updates.md#:~:text=Queueing%20a%20Series%20of%20State%20Updates)

现有的译法：
1. 把（将）……加入队列
3. 使……入列
2. 排列……

**Comment by yyyang1996** [comment]
和 prop 类似，dispatch actions 不翻译，对熟悉 redux 的人友好一些。

**Comment by KimYangOfCat** [comment]
state 应该如何翻译？
根据根据原本[官网上的翻译](https://zh-hans.reactjs.org/docs/state-and-lifecycle.html)，应该是作为一个独特概念，不翻译，但是在beta文档的翻译中似乎没有做统一？有些没有翻译，有些翻译为“状态”。
参考：#692

我个人支持不翻译，和以前保持一致

**Comment by KimYangOfCat** [comment]
UI 应如何翻译？
UI？ 还是译为 用户界面？
参考：#692

**Comment by KimYangOfCat** [comment]
代码注释有必要翻译为中文吗？
个人认为没有必要，内容相对简单，理解门槛不高，但对于后期文档维护的工作量会增加很多。

**Comment by BBboy01** [comment]
> state 应该如何翻译？ 根据原本[官网上的翻译](https://zh-hans.reactjs.org/docs/state-and-lifecycle.html)，应该是作为一个独特概念，不翻译，但是在beta文档的翻译中似乎没有做统一？有些没有翻译，有些翻译为“状态”。 参考：#692
但并非所有的 state 都表示 react 中特有 state，例如 156 行状态机的解释（处于多种“状态”中）

**Comment by KimYangOfCat** [comment]
@BBboy01 这确实是存在，之前是我没有考虑清楚，抱歉。我认为最好区分一下这两种场景：
1. 若是描述具体组件状态时，译为“状态”是合理的；
2. 若是特指 react 中的 state 对象，那么应该保留英文

**Comment by BBboy01** [comment]
> @BBboy01 这确实是存在，之前是我没有考虑清楚，抱歉。我认为最好区分一下这两种场景：
> 
> 1. 若是描述具体组件状态时，译为“状态”是合理的；
> 2. 若是特指 react 中的 state 对象，那么应该保留英文

没关系，我现在做了区分，你看看还有哪些 state 翻译的不合理吧。
