### ISSUE TITLE
Where do we translate http://beta.reactjs.org?

### ISSUE THREAD

**Issue by zzz6519003** [reactjs/zh-hans.reactjs.org#766]

**Comment by awxiaoxian2020** [comment]
It seems that there is no [deployment](https://github.com/reactjs/reactjs.org/issues/4135) for zh-cn. @QC-L

**Comment by ifshizuku** [comment]
Is there anyone who can communicate with the translation team about the **beta version** translation?

**Comment by awxiaoxian2020** [comment]
It seems that we can make a PR to the folder `beta` directly.

**Comment by zzz6519003** [comment]
@Huxpro ?

**Comment by awxiaoxian2020** [comment]
@zzz6519003 You can see many prefix `[New Docs]` in the issues. Is it what you want?

**Comment by QC-L** [comment]
For the time being, people can visit https://cn-beta-reactjs.vercel.app/

**Comment by awxiaoxian2020** [comment]
> It seems that we can make a PR to the folder `beta` directly.

I think it's clear, closing.

**Comment by zzz6519003** [comment]
> For the time being, people can visit https://beta.react.jscn.org

@QC-L  https://beta.react.jscn.org/ 应该把自己的source链接标在网页里
