### ISSUE TITLE
Update the wiki about the 404 link.

### ISSUE THREAD

**Issue by awxiaoxian2020** [reactjs/zh-hans.reactjs.org#788]
Please update the wiki about the 404 link [中文文案排版指南](https://github.com/sparanoid/chinese-copywriting-guidelines/blob/master/README.zh-CN.md) in [React-中文文档译文排版指南](https://github.com/reactjs/zh-hans.reactjs.org/wiki/React-%E4%B8%AD%E6%96%87%E6%96%87%E6%A1%A3%E8%AF%91%E6%96%87%E6%8E%92%E7%89%88%E6%8C%87%E5%8D%97). It should be updated to https://github.com/sparanoid/chinese-copywriting-guidelines/blob/master/README.zh-Hans.md.

**Comment by QC-L** [comment]
Fixed!
