### ISSUE TITLE
The progress of translating beta docs

### ISSUE THREAD

**Issue by KelvinQiu802** [reactjs/zh-hans.reactjs.org#880]
下面文章已经在中文官网中显示，但是没有被翻译，也没有出现在todo中
- ESCAPE HATCHES
   - Synchronizing with Effects
   - You Might Not Need an Effect

我愿意为上面文章提供翻译。

**Comment by cw1997** [comment]
按照之前的规则，似乎翻译请求都是回复在https://github.com/reactjs/zh-hans.reactjs.org/issues/4 这里面，但是现在看来那个issue一直无人回复，不知现在的翻译流程和规则是什么

**Comment by awxiaoxian2020** [comment]
@cw1997 @KelvinQiu802 We must handle with exsited PRs first.

**Comment by awxiaoxian2020** [comment]
It will be tracked in #1075
